id: P499E311E
initial_creation_type: input
source_metadata:
  Title: Ātreyatilaka
  Editor: Janardan Pandey
  Publisher: Central Institute of Higher Tibetan Studies (CIHTS)
  Place of Publication: Sarnath, Varanasi, India
  Year: '2003'
  Ātreyatilakam:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
created_at: '2022-03-08T16:51:56.880195'
last_modified_at: '2022-03-08T16:51:56.880205'
